BUFFER_SIZE = 1024

DEBUG_MODE = False

SERVER_MESSAGE = 'server_message'
SERVER_DETAILS = 'server_details'
USER_MESSAGE = 'user_message'
USER_LEFT = 'user_left'

CLIENT_SCREEN_WIDTH = 720
CLIENT_SCREEN_HEIGHT = 420

LAUNCHER_SCREEN_WIDTH = 350
LAUNCHER_SCREEN_HEIGHT = 120

ARGUMENTS_LENGTH = 3