CONFIG_FILE_LOCATION = 'config.ini'

DEFAULT_HOST_NAME = 'uSpeak711 server'

DEFAULT_SERVER_PORT = 7777

DEFAULT_SERVER_RCON = 'changeme'

DEFAULT_MAX_USERS = 10

MAX_BUFFER = 1024

USERNAME_BUFFER = 52

MAX_LOAD_MESSAGES_COUNT = 5

SERVER_MESSAGE = 'server_message'

SERVER_DETAILS = 'server_details'

DEFAULT_CHANNELS = "news,general,offtopic"